### ISSUE TITLE
Bump django-filter version

### ISSUE THREAD

**Issue by norbeta** [nuxis/p0sX-server#31]
### Feature or Bug?
- [ ] Feature
- [X] Bug

### Bug
p0sx-client not able to fetch data, error 500

#### Description
After dependabot upgraded Django and DRF, old version of django-filter is not working anymore. 

**Possible Solution**
Bump django-filter==1.1.0

**Comment by norbeta** [comment]
#32 fixes this.

**Comment by bgbak** [comment]
Merged #32
